# SPDX-FileCopyrightText: Contributors to the Transformer Thermal Model project
#
# SPDX-License-Identifier: MPL-2.0

# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # enable version updates for our dependencies
  - package-ecosystem: "pip" # `pip` also enables Poetry
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"

  # enable version updates for our pre-commit hooks.
  - package-ecosystem: "pre-commit"
    directory: "/"
    schedule:
      interval: "weekly"

  # enable version updates for our pre-commit hooks
  - package-ecosystem: "github-actions"
    # Workflow files stored in the default location of `.github/workflows`
    # You don't need to specify `/.github/workflows` for `directory`. You can use `directory: "/"`.
    directory: "/"
    schedule:
      interval: "weekly"
