# SPDX-FileCopyrightText: Contributors to the Transformer Thermal Model project
#
# SPDX-License-Identifier: MPL-2.0
name: (CI) Build Package
permissions:
  contents: read
on:
  push

jobs:
  build-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Build package
        run: poetry build

      - name: Upload package artifact
        uses: actions/upload-artifact@v4
        with:
          name: transformer-thermal-model-package
          path: dist/
  