# SPDX-FileCopyrightText: Contributors to the Transformer Thermal Model project
#
# SPDX-License-Identifier: MPL-2.0

name: |
  (T) Pytest
permissions:
  contents: read
  pull-requests: write

on:
  push:
    inputs:
      python-version:
        required: false
        type: string
        default: '3.12'
        description: 'Python version used.'

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Install python${{ inputs.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version:  ${{ inputs.python-version }}
      - name: Install Poetry
        run: pipx install --python python${{ inputs.python-version }} poetry
      - name: Install the library using poetry
        shell: bash
        run: poetry install --with dev
      - name: Unit tests
        if: ${{ hashFiles('tests/') != '' }}
        shell: bash
        run: poetry run pytest
      - name: Upload coverage.xml as artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a #v7.0.1
        if: ${{ hashFiles('coverage.xml') != '' }}
        with:
          name: coverage.xml
          path: ./coverage.xml
      - name: SonarQube Scan
        # dependabot cannot access these secrets (see 
        # https://github.com/dependabot/dependabot-core/issues/3253#issuecomment-852541544
        # for more info. We need this SonarQube scan for the coverage report,
        # so we still want it here for our own pushes.
        if: github.actor != 'dependabot[bot]'
        uses: SonarSource/sonarqube-scan-action@299e4b793aaa83bf2aba7c9c14bedbb485688ec4 #v7.1.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}