# SPDX-FileCopyrightText: Contributors to the Transformer Thermal Model project
#
# SPDX-License-Identifier: MPL-2.0
name: REUSE Compliance Check
permissions:
  contents: read
  pull-requests: write

on:
  push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-reuse-compliance
  cancel-in-progress: true

jobs:
  reuse-compliance-check:
    runs-on: ubuntu-24.04
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: REUSE Compliance Check
      uses: fsfe/reuse-action@v5