# SPDX-FileCopyrightText: Contributors to the Transformer Thermal Model project
#
# SPDX-License-Identifier: MPL-2.0

# This workflow is used to run the example notebooks and check if they execute without raising any exceptions.
name: Run Example Notebooks
permissions:
  contents: read
  pull-requests: read

env:
  python-version: '3.12'

on:
  push:  
    branches: [ "main" ]  
  pull_request:  
    branches: [ "main" ]

jobs:
  check-notebooks:
    runs-on:
        group: managed-linux
    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Install python${{ env.python-version }}
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: ${{ env.python-version }}
      - name: Install uv
        run: pipx install --python python${{ env.python-version }} uv==0.11.31
      - name: Install the dependencies using uv
        shell: bash
        run: uv sync --group docs --no-install-project --no-build --frozen
      - name: Run example notebooks
        env:
          PYTHONPATH: ${{ github.workspace }} # Set PYTHONPATH to the root of the repository to ensure that the library can be imported in the notebooks
        run: |
          for notebook in docs/examples/*.ipynb; do
            uv run --no-sync --no-build jupyter nbconvert --to notebook --execute "$notebook"
          done